### ISSUE TITLE
Proposal: Rename Package & Repo to `BEP032tools`

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/BEP032tools#103]
To improve the findability and visibility of this repo it would be good to have a name resembling the link to the BEP032 proposal: https://bids.neuroimaging.io/bep032

**Comment by JuliaSprenger** [comment]
If there's no objections from your side @SylvainTakerkart I would like to change the name this week to have it updated for the presentations next week. @killianrochet The old name should still be working as an alias as far as I know, but if you experience trouble accessing the repo after the name change then tell me.

**Comment by JuliaSprenger** [comment]
@SylvainTakerkart @killianrochet I changed the repo name and the also the old url should be automatically redirected. However for future consistency, it would be good to update the remotes of existing clones using `git remote set-url upstream git@github.com:INT-NIT/BEP032tools.git` (assuming you labelled this repo here as `upstream`).

**Comment by SylvainTakerkart** [comment]
yes, go for it!

**Comment by JuliaSprenger** [comment]
solved by #105
