### ISSUE TITLE
BEP032Validator package is missing on pypi

### ISSUE THREAD

**Issue by ree-gupta** [INT-NIT/BEP032tools#118]
BEP032Validator package is missing on pypi: https://pypi.org/project/BEP032tools/ gives a 404 Error. I think it was not renamed, maybe? because AnDOChecker installs flawlessly: https://pypi.org/project/AnDOChecker/

**Comment by JuliaSprenger** [comment]
Hi @ree-gupta !
Thanks for the note. We didn't do a release of the package since the renaming from `AnDO` to `BEP032tools`. Will do this as soon as possible.

Todo List for myself:

- [ ] update readme install instructions to use `BEP032tools` package
- [ ] make a release on PyPi
