### ISSUE TITLE
Modularize interface for webserver

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/BEP032tools#58]
Currently, the design of Ando integrates two things at once. The core functionality of testing if a particular dataset adheres to AnDO and providing an interface for the webserver. This is partially confusing, since return values for the webserver are bash-style (0:successful, >0: Error), whereas in the core python implementation 0 (=False) would be a negative result of a test and vv.

I think we can solve this by moving the interface for the server to a submodule (tool) that does the translation between these two approaches.

**Comment by SylvainTakerkart** [comment]
Thanks for catching this! Yes, this sounds good... Maybe we can address this later (i.e after our current major update), since our priority is on the CLI...

**Comment by JuliaSprenger** [comment]
The server interface has been removed. This issue is outdated. Closing now.
