### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Slowblitz** [INT-NIT/BEP032tools#99]
Hey, it seems that the documentation in not up to date on read the docs

**Comment by Remi-Gau** [comment]
Actually it'd be nice to have link to the online RTD. :-)

**Comment by JuliaSprenger** [comment]
With the latest renaming of the project to BEP032tools we also need to set up the project again on RTD as the project slug / documentation url can not be updated there for an existing project. Also the webhook integration currently does not seem to work between RTD and github.

**Comment by JuliaSprenger** [comment]
I updated the integration with rdt and added the link to the documentation on RTD to the readme ([af2a640](https://github.com/INT-NIT/BEP032tools/pull/128/commits/af2a640d23e052b2b6300620e577b9ee5698712b))
